= Hardware Description
:imagesdir: images


== Core Module

This module is a fundamental element of every BigClown node.
Its most important components are ARM microcontroller and 868 MHz radio module.
Core Module can be programmed using USB DFU bootloader which is stored in ROM memory of the microcontroller or it can be debugged via a standard 10-pin SWD probe.
Combination of these features, integrated security chip, temperature sensor and accelerometer makes this an unrivaled solution for today’s connected home automation nodes.

Features:

* ARM Cortex M0+ 32-bit MCU STM32L083CZ
* 192 kB Flash / 20 kB RAM
* Radio module (868 MHz) based on SPIRIT1
* Security chip ATSHA204A
* Digital temperature sensor TMP112
* 3-axis accelerometer LIS2DH12
* Red color LED
* Push button RESET and BOOT (BOOT is available to MCU)
* 10-pin SWD connector for debugging
* Micro-USB for hostcommunication and/or power
* Integrated USB DFU bootloader (no need for pre-programmed chip)
* 18x GPIO (completely free for application)
* 3x UART
* 2x I^2^C
* 1x SPI
* 5x ADC
* 2x DAC
* Deep sleep mode: < 5 µA
* Operating voltage range: 2.0 V to 3.6 V
* Operating temperature range: -20 to 70 °C
* Mechanical dimensions: 33 x 55 mm
* 10-year warranty


== Base Module

This module works as a mechanical stand for a  BigClown node.
With the exception of Battery Module you can plug any other BigClown module into a standardized socket available on Base Module.
This module can be used as a stand on a desk (four rubber feets assure stable position on a surface), mounted on a DIN rail using special plastic clips, or it can be sticked on a wall or other vertical surfaces using a double-sided tape.
The additional feature of this module is a prototyping area for soldering your own circuits.

Features:

* Practical stand for BigClown module system
* Prototyping area for soldering custom circuits
* Rubber feets (included)
* Plastic clips for a DIN rail mount (optional accessory)
* Operating temperature range: -20 to 70 °C
* Mechanical dimensions: 88 x 55 mm
* 10-year warranty


== Battery Module

Battery Module is designed as a power supply source for battery-operated nodes.
Using a low-power buck converter provides excellent efficiency and long battery lifetime from four AAA 1.5 V Alkaline cells.
Load disconnect circuit can bypass batteries if any other power supply source is connected in the system (e.g. AC adapter or USB cable).
Battery voltage can be measured on one of the analog inputs of the standardized header.
Battery Module also provides an extra 5-pin socket allowing to connect a BigClown tag (I^2^C peripheral in a common form factor).
Another useful feature is a prototyping area for soldering your own circuits.

Features:

* High efficiency buck converter TPS62745
* Ultra low quiescent current: 400 nA
* Recommended battery types:
* 4x AAA 1.5 V Alkaline or
* 4x AAA Eneloop NiMH
* Output supply voltage 3.1 V
* Battery disconnect circuit
* Input voltage measurement using ADC input
* Prototyping soldering area for soldering custom circuits
* An extra position for BigClown tag
* Ready for NFC Module (coming in 2017)
* Operating temperature range: -20 to 70 °C
* Mechanical dimensions: 88 x 55 mm
* 10-year warranty


== Breadboard Module

Everybody loves breadboards, right?
And Breadboard Module offers an easy way to connect any BigClown module to a breadboard.
Narrow breakout of Breadboard Module provides more space for wiring and prototyping.
Optimized precision pin headers from the bottom side allow smooth insertion to your breadboard and prevent its damage.

Features:

* Adapter between BigClown modules and breadboard
* Precision pin headers optimized for breadboard sockets
* Operating temperature range: -20 to 70 °C
* Mechanical dimensions: 113.7 x 33 mm
* 10-year warranty


== Bridge Module

In some cases a wireless connectivity and versatility of Core Module is not necessary and Bridge Module provides an easy path to connect some of the BigClown modules and/or tags to a USB host like Raspberry Pi or any desktop/laptop computer.
MicroUSB connector not only provides communication link but also delivers power for Bridge Module and peripherals connected to it.
This product is based on FTDI's chip FT260 which is a USB HID to I^2^C/UART converter.
This capability makes Bridge Module an ideal tool for interfacing I^2^C/UART peripherals from your Linux environment.

Features:

* Integrated USB HID to I^2^C/UART converter FT260
* Micro-USB connector
* Two independent I^2^C buses provided by I^2^C multiplexer TCA9543
* Red color LED (driven from FT260 GPIO pin)
* Operating voltage range: 3.0 to 3.6 V or from USB host
* Operating temperature range: -20 to 70 °C
* Mechanical dimensions: 33 x 55 mm
* 10-year warranty

Hardware / software compatibility:

* Temperature Tag
* Humidity Tag
* Lux Meter Tag
* Barometer Tag
* Tag Module
* Relay Module
* CO2 Module
* Base Module
* Breadboard Module
* Probe Module


== CO2 Module

Carbon dioxide (or CO^2^) is a colorless and odorless gas that is vital to life on Earth.
Its nominal concentration is about 400 ppm (0.04 %).
There are many occurrences of CO2 in nature.
For example humans produce CO2 using their respiration system during the exhalation phase.
High concentration of CO2 leads to acidity and various health related problems.
This is what motivated us to develop CO2 Module.
This module achieves ±50 ppm accuracy using a non-dispersive infrared (NDIR) sensor LP8 designed by SenseAir company from Sweden.
Thanks to its low-power operation it can be powered from batteries for years.
BigClown has equipped LP8 sensor with additional circuitry for efficient power management and I^2^C-only interfacing.
Enhancing your environmental monitoring with CO2 Module from BigClown has never been easier.
Last but not least feature of this module are three extra 5-pin sockets allowing to connect BigClown tags (I^2^C peripheral in a common form factor).

Features:

* Carbon dioxide (CO2) sensor LP8
* Non-dispersive infrared (NDIR) technology developed by SenseAir (Sweden)
* Measurement range CO2: 0 to 10 000 ppm
* Accuracy: ±50 ppm CO2 ±3 % of reading (1)
* I^2^C-only interface (integrated UART bridge and I/O expander)
* Constant current source for 470mF supercap
* Long battery life time
* 3x position for BigClown tags
* Low power consumption:
* 6 µA (six measurements per hour)
* 61 µA (one measurement per minute)
* Operation voltage range: 3 V to 3.6 V
* Operating temperature range: 0 to 50 °C
* Mechanical dimensions: 88 x 55 mm
* 10-year warranty

Note (1): Accuracy ±50 ppm is achieved after 24 days of operation and auto calibration process.


== Power Module

This module allows to connect 5 V DC wall adapter via a standard 2.1 mm power jack socket.
With this module a BigClown node can be powered using its integrated LDO which generates 3.3 V output from a 5 V input.
Another feature is a high-current relay (230 V AC / 16 A).
Moreover you can directly connect (via a 3-terminal block) a programmable RGB(W) LED strip with 5V interface (voltage translation logic is implemented) which is great for driving WS2812B-compatible LEDs.
Reliability is as important for us as it is for you.
That's why we have implemented smart overvoltage, undervoltage and reverse polarity protection on the power jack input to guarantee the input voltage range to always stay within the proper limits.
Last but not least feature of this module are two extra 5-pin sockets allowing to connect a BigClown tags (I^2^C peripheral in a common form factor).

Features:

* 5 V DC adapter input (2.1mm jack) (1)
* Input voltage range from 4.2 V to 5.8 V
* High-current relay output (230 V AC / 16 A)
* Integrated LDO with 3.3 V output voltage
* Addressable RGB(W) LED strip output (1) (2)
* 2x position for BigClown tag
* Overvoltage, undervoltage and reverse polarity protection
* Pluggable 3-pin terminal block for relay output
* Pluggable 3-pin terminal block for LED strip
* Operating temperature range: -20 to 70 °C
* Mechanical dimensions: 88 x 55 mm
* 10-year warranty

(1) Maximum allowed is 6 A
(2) Core Module is required to drive an addressable LED strip


== Probe Module

Sometimes you need to measure signals during both hardware and software development cycle.
And to see what's going on, you need to quickly hook up an appropriate equipment like like oscilloscope, logic analyzer, etc.
We have made that task simple with Probe Module.
This module is an electro-mechanical interface between test points - the "O"-shaped hooks connected to signals on BigClown header - and your equipment's probes.

Features:

* Test points for all signals available on BigClown header
* Four plated holes (in every corner) for comfortable ground clip connection
* Operating temperature range: -20 to 70 °C
* Mechanical dimensions: 88 x 55 mm
* 10-year warranty


== Relay Module

Relay Module is suitable for switching small power appliances - e.g. LED strip, cooling fan, siren, buzzer, garage door opener, etc.
A cool feature of this module is a latching relay (also called bistable relay).
This feature makes this module suitable for battery-operated applications.
What does it mean?
For this type of relay the energy is needed only during transition state of the relay.
Once the new state has been set it is not necessary to energize the coil anymore - it will simply "remember" (or latch) its state.
Switching period is indicated using green LED (software defined "true state"), or using red LED (software defined "false state").
This module is I^2^C-only peripheral so it does not allocate any extra signals from BigClown header.

Features:

* Bistable (latching) relay for switching loads up to 60 W:
** 12 V DC / 5 A
** 24 V DC / 2.5 A
* Suitable for battery-operated applications
* Energy is needed only during coil transition states
* I2C-only peripheral
* Red and green LEDs indicating coil transition
* Operation voltage range: 3.0 to 3.6 V
* Operating temperature range: -20 to 70 °C
* Mechanical dimensions: 33 x 55 mm
* 10-year warranty


== Tag Module

Some BigClown modules have one or more extra 5-pin sockets allowing to connect a BigClown tag (I^2^C peripheral in a common form factor).
But sometimes this is still not enough or you need to extend the I^2^C bus with an additional channel.
Tag Module enables to connect up to six extra tags.
Every tag has a unique I^2^C address.
Using two independent I^2^C buses (I2C0 and I2C1) makes it possible to connect two tags of the same address to a single BigClown node.

Features:

* 6 x 5-pin socket position for BigClown tag (I^2^C peripheral)
* 3x tag connected to I2C0
* 3x tag connected to I2C1
* Operating temperature range: -20 to 70 °C
* Mechanical dimensions: 44 x 55 mm
* 10-year warranty
